# Makefile - build script */
# Copyright (C) 2013 Goswin von Brederlow <goswin-v-b@web.de>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# source files
SOURCES  := $(wildcard *.cc)

# object files
OBJS        += $(patsubst %.cc,%.o,$(SOURCES))

# build dir
BUILD_DIR	= ../build

# Build flags
CXXFLAGS    := -O2 -W -Wall -g

# build rules
all: raspbootcom

raspbootcom: raspbootcom.o
	mkdir -p $(BUILD_DIR)
	clang -o $(BUILD_DIR)/$@ $+

clean:
	$(RM) -f $(OBJS) $(BUILD_DIR)/raspbootcom

dist-clean: clean
	find -name "*~" -delete
	find -name "*.d" -delete

# C++.
%.o: %.cc Makefile
	clang $(CXXFLAGS) -c $< -o $@

upload:
	$(BUILD_DIR)/raspbootcom /dev/tty.SLAB_USBtoUART /Users/vladimir/Dev/Zig/hos/zig-cache/bin/kernel.img 

# /Users/vladimir/Dev/Zig/raspi3-tutorial/03_uart1/kernel8.img 

# /Users/vladimir/Dev/Zig/kernel_test/zig-cache/kernel.img 


# $(BUILD_DIR)/kernel.img
